export { default as Navigation } from "./Navigation";
export { default as Navigationfr } from "./Navigationfr";
export { default as Navigationes } from "./Navigationes";
export { default as Navigationge } from "./Navigationge";
export { default as Navigationne } from "./Navigationne";
export { default as Footer } from "./Footer";
export { default as Home } from "./Home";
export { default as Contact } from "./Contact";
export { default as Blog } from "./Blog";
export { default as Postphotography } from "./Postphotography";
// export { default as Topshopify } from "./top-shopify-marketing-strategy-for-sellers";
// export { default as Videoediting } from "./5-interesting-video-editing-facts";
